#!/usr/bin/env bash
# https://rock-it.pl/automatic-code-quality-checks-with-git-hooks/
# This command creates symlink to our pre-commit scripts.

GIT_DIR=$(git rev-parse --git-dir)

echo "Installing hooks..."
ln -s ../../scripts/pre-commit $GIT_DIR/hooks/pre-commit
echo "Done!"
